package com.jintoufs.zj.transfercabinet.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jintoufs.zj.transfercabinet.db.CabinetInfo;

import com.jintoufs.zj.transfercabinet.db.CabinetInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cabinetInfoDaoConfig;

    private final CabinetInfoDao cabinetInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cabinetInfoDaoConfig = daoConfigMap.get(CabinetInfoDao.class).clone();
        cabinetInfoDaoConfig.initIdentityScope(type);

        cabinetInfoDao = new CabinetInfoDao(cabinetInfoDaoConfig, this);

        registerDao(CabinetInfo.class, cabinetInfoDao);
    }
    
    public void clear() {
        cabinetInfoDaoConfig.getIdentityScope().clear();
    }

    public CabinetInfoDao getCabinetInfoDao() {
        return cabinetInfoDao;
    }

}
